// save us one ajax call that we will always have to make
// this can also be grabbed by navigating to /epub_content/metadata.json
window.ReadiumLibraryData = [
	{
		"fixed_layout":false,
		"open_to_spread":false,
		"cover_href":"/images/library/missing-cover-image.png",
		"created_at":"2012-03-27T19:22:01.521Z",
		"updated_at":"2012-03-27T19:23:38.309Z",
		"key":"1",
		"src_url":"http://code.google.com/p/epub-samples/downloads/list",
		"package_doc_path":"/epub_content/1/EPUB/package.opf",
		"id":"code.google.com.epub-samples.linear-algebra",
		"epub_version":"3.0",
		"title":"A First Course in Linear Algebra",
		"author":"Robert A. Beezer",
		"publisher":"",
		"description":"",
		"rights":"This work is shared with the public using the GNU Free Documentation License, Version 1.2.",
		"language":"en",
		"pubdate":"",
		"modified_date":"2012-03-05T12:47:00Z",
		"layout":"",
		"spread":"",
		"orientation":"",
		"ncx":""
	},
	{
		"fixed_layout":false,
		"open_to_spread":false,
		"cover_href":"/epub_content/2/EPUB/images/portrait.jpg",
		"created_at":"2012-03-27T19:24:45.543Z",
		"updated_at":"2012-03-27T19:25:00.094Z",
		"key":"2",
		"src_url":"http://code.google.com/p/epub-samples/downloads/list",
		"package_doc_path":"/epub_content/2/EPUB/cole.opf",
		"id":"code.google.com.epub-samples.cole-voyage-of-life",
		"epub_version":"3.0",
		"title":"Thomas Cole - The Voyage of Life",
		"author":"Jesse Dylan",
		"publisher":"",
		"description":"",
		"rights":"This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.",
		"language":"en-US",
		"pubdate":"",
		"modified_date":"2012-03-20T11:37:00Z",
		"layout":"",
		"spread":"",
		"orientation":"",
		"ncx":""
	},{
		"fixed_layout":false,
		"open_to_spread":false,
		"cover_href":"/epub_content/3/EPUB/wasteland-cover.jpg",
		"created_at":"2012-03-27T19:25:40.235Z",
		"updated_at":"2012-03-27T19:26:06.326Z",
		"key":"3",
		"src_url":"http://code.google.com/p/epub-samples/downloads/list",
		"package_doc_path":"/epub_content/3/EPUB/wasteland.opf",
		"id":"code.google.com.epub-samples.wasteland-basic","epub_version":"3.0",
		"title":"The Waste Land","author":"T.S. Eliot",
		"publisher":"",
		"description":"",
		"rights":"This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		"language":"en-US",
		"pubdate":"2011-09-01",
		"modified_date":"2012-01-18T12:47:00Z",
		"layout":"",
		"spread":"",
		"orientation":"",
		"ncx":"ncx"
	},{
		"fixed_layout":true,
		"open_to_spread":false,
		"cover_href":"/epub_content/4/EPUB/Image/cover.jpg",
		"created_at":"2012-03-28T18:24:18.450Z",
		"updated_at":"2012-03-28T18:25:32.553Z",
		"key":"4",
		"src_url":"http://code.google.com/p/epub-samples/downloads/list",
		"package_doc_path":"/epub_content/4/EPUB/package.opf",
		"id":"urn:uuid:d5803940-647f-11e1-ad77-0002a5d5c51b",
		"epub_version":"3.0",
		"title":"Page Blanche","author":"Boulet",
		"publisher":"éditions Delcourt",
		"description":"",
		"rights":"This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		"language":"fr",
		"pubdate":"2012-01-18",
		"modified_date":"2012-03-06T12:00:00Z",
		"layout":"pre-paginated",
		"spread":"auto",
		"orientation":"auto",
		"ncx":""
	}, {
		"author": "Mary Webb",
		"cover_href": "/images/library/missing-cover-image.png",
		"created_at": "2012-04-10T21:47:53.353Z",
		"description": "",
		"epub_version": "2.0",
		"fixed_layout": false,
		"id": "urn:uuid:ADDB2B4D-BA43-4DE9-8BAB-CF8759C8F843",
		"key": "3921047c34132ab12338059f09bbf5c8",
		"language": "en-gb",
		"layout": "",
		"modified_date": "",
		"ncx": "ncx",
		"open_to_spread": false,
		"orientation": "",
		"package_doc_path": "/epub_content/5/OPS/content.opf",
		"pubdate": "2002",
		"publisher": "epubBooks (www.epubbooks.com)",
		"rights": "↵            Provided for free by epubBooks.com. Not for commercial use.↵            This EPUB eBook is released under a Creative Commons (BY-NC-ND/3.0) Licence.↵            Source text and images are in the Public Domain.↵      ",
		"spread": "",
		"src_url": "webb-precious-bane.epub",
		"title": "Precious Bane",
		"updated_at": "2012-04-10T21:48:57.267Z"
	}, {
		"apple_fixed": false,
		"author": "EPUB 3 Working Group",
		"cover_href": "/epub_content/epub30_spec/EPUB/img/epub_logo_color.jpg",
		"created_at": "2012-06-15T00:05:56.371Z",
		"description": "",
		"epub_version": "3.0",
		"fixed_layout": false,
		"id": "code.google.com.epub-samples.epub30-spec",
		"key": "epub30_spec",
		"language": "en",
		"layout": "",
		"modified_date": "2012-02-27T16:38:35Z",
		"ncx": "",
		"open_to_spread": false,
		"orientation": "",
		"package_doc_path": "/epub_content/epub30_spec/EPUB/package.opf",
		"page_prog_dir": "",
		"paginate_backwards": false,
		"pubdate": "",
		"publisher": "",
		"rights": "",
		"spread": "",
		"src_url": "http://code.google.com/p/epub-samples/downloads/list",
		"title": "EPUB 3.0 Specification",
		"updated_at": "2012-06-15T00:06:37.334Z"
	}, {
		"apple_fixed": false,
		"author": "",
		"cover_href": "/images/library/missing-cover-image.png",
		"created_at": "2012-06-15T00:05:56.371Z",
		"description": "",
		"epub_version": "3.0",
		"fixed_layout": false,
		"id": "http://www.aozora.gr.jp/cards/000148/card776.html",
		"key": "kusamakura",
		"language": "ja-jp",
		"layout": "",
		"modified_date": "2012-04-24T00:00:00Z",
		"ncx": "ncxtoc",
		"open_to_spread": false,
		"orientation": "",
		"package_doc_path": "/epub_content/kusamakura/OPS/package.opf",
		"page_prog_dir": "rtl",
		"paginate_backwards": false,
		"pubdate": "",
		"publisher": "",
		"rights": "",
		"spread": "",
		"src_url": "http://code.google.com/p/epub-samples/downloads/list",
		"title": "草枕",
		"updated_at": "2012-06-15T00:06:55.212Z"
	}, {
		"apple_fixed": false,
		"author": "Herman Melville",
		"cover_href": "/epub_content/moby_dick/OPS/images/9780316000000.jpg",
		"created_at": "2012-06-15T00:05:56.371Z",
		"description": "",
		"epub_version": "3.0",
		"fixed_layout": false,
		"id": "code.google.com.epub-samples.moby-dick-basic",
		"key": "moby_dick",
		"language": "en-US",
		"layout": "",
		"modified_date": "2012-01-18T12:47:00Z",
		"ncx": "",
		"open_to_spread": false,
		"orientation": "",
		"package_doc_path": "/epub_content/moby_dick/OPS/package.opf",
		"page_prog_dir": "",
		"paginate_backwards": false,
		"pubdate": "",
		"publisher": "Harper & Brothers, Publishers",
		"rights": "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		"spread": "",
		"src_url": "http://code.google.com/p/epub-samples/downloads/list",
		"title": "Moby-Dick",
		"updated_at": "2012-06-15T00:07:21.516Z"
	}, {
		"apple_fixed": false,
		"author": "",
		"cover_href": "/epub_content/trees/EPUB/cover.jpg",
		"created_at": "2012-06-15T00:05:56.371Z",
		"description": "Test of canvas element and CSS3 multi-column layout",
		"epub_version": "3.0",
		"fixed_layout": false,
		"id": "code.google.com.epub-samples.trees",
		"key": "trees",
		"language": "en",
		"layout": "",
		"modified_date": "2012-04-05T12:47:00Z",
		"ncx": "",
		"open_to_spread": false,
		"orientation": "",
		"package_doc_path": "/epub_content/trees/EPUB/package.opf",
		"page_prog_dir": "",
		"paginate_backwards": false,
		"pubdate": "",
		"publisher": "",
		"rights": "",
		"spread": "",
		"src_url": "http://code.google.com/p/epub-samples/downloads/list",
		"title": "Trees",
		"updated_at": "2012-06-15T00:07:49.803Z"
	}, {
		"apple_fixed": false,
		"author": "",
		"cover_href": "/images/library/missing-cover-image.png",
		"created_at": "2012-06-15T00:08:27.336Z",
		"description": "",
		"epub_version": "3.0",
		"fixed_layout": true,
		"id": "urn:uuid:A649F639-6C1F-1014-8CC3-F813564D7508",
		"key": "haruko",
		"language": "ja-jp",
		"layout": "pre-paginated",
		"modified_date": "2012-05-24T00:00:00Z",
		"ncx": "ncxtoc",
		"open_to_spread": false,
		"orientation": "portrait",
		"package_doc_path": "/epub_content/haruko/OPS/package.opf",
		"page_prog_dir": "rtl",
		"paginate_backwards": false,
		"pubdate": "",
		"publisher": "",
		"rights": "",
		"spread": "landscape",
		"src_url": "http://code.google.com/p/epub-samples/downloads/list",
		"title": "ハルコさんの彼氏",
		"updated_at": "2012-06-15T00:08:36.776Z"
	}, {
		"apple_fixed": false,
		"author": "",
		"cover_href": "/images/library/missing-cover-image.png",
		"created_at": "2012-06-15T00:08:27.336Z",
		"description": "",
		"epub_version": "3.0",
		"fixed_layout": false,
		"id": "code.google.com.epub-samples.hefty.water",
		"key": "hefty_water",
		"language": "en",
		"layout": "",
		"modified_date": "2012-03-29T12:00:00Z",
		"ncx": "",
		"open_to_spread": false,
		"orientation": "",
		"package_doc_path": "/epub_content/hefty_water/EPUB/package.opf",
		"page_prog_dir": "",
		"paginate_backwards": false,
		"pubdate": "2012-03-29",
		"publisher": "",
		"rights": "",
		"spread": "",
		"src_url": "http://code.google.com/p/epub-samples/downloads/list",
		"title": "Hefty Water",
		"updated_at": "2012-06-15T00:09:37.681Z"
	}, {
		"apple_fixed": false,
		"author": "Matt Garrish",
		"cover_href": "/epub_content/accessible_epub_3/EPUB/covers/9781449328030_lrg.jpg",
		"created_at": "2012-06-15T00:10:25.327Z",
		"current_margin": 1,
		"current_theme": "default-theme",
		"description": "",
		"epub_version": "3.0",
		"fixed_layout": false,
		"font_size": 10,
		"id": "urn:isbn:9781449328030",
		"key": "accessible_epub_3",
		"language": "en",
		"layout": "",
		"modified_date": "2012-02-20T22:17:24Z",
		"ncx": "ncx",
		"open_to_spread": false,
		"orientation": "",
		"package_doc_path": "/epub_content/accessible_epub_3/EPUB/package.opf",
		"page_prog_dir": "",
		"paginate_backwards": false,
		"pubdate": "2012",
		"publisher": "O’Reilly Media, Inc.",
		"rights": "Copyright © 2012 O’Reilly Media, Inc",
		"spread": "",
		"src_url": "http://code.google.com/p/epub-samples/downloads/list",
		"title": "Accessible EPUB 3",
		"two_up": true,
		"updated_at": "2012-06-15T00:13:26.319Z"
	}, {
		"apple_fixed": false,
		"author": "Pr David Khayat",
		"cover_href": "/epub_content/regime_anticancer_arabic/EPUB/Image/cover.jpg",
		"created_at": "2012-06-15T00:11:17.450Z",
		"description": "",
		"epub_version": "3.0",
		"fixed_layout": false,
		"id": "code.google.com.epub-samples.regime-anticancer-arabic",
		"key": "regime_anticancer_arabic",
		"language": "ar",
		"layout": "",
		"modified_date": "2012-03-26T12:00:00Z",
		"ncx": "ncx",
		"open_to_spread": false,
		"orientation": "",
		"package_doc_path": "/epub_content/regime_anticancer_arabic/EPUB/package.opf",
		"page_prog_dir": "rtl",
		"paginate_backwards": false,
		"pubdate": "2012",
		"publisher": "Hachette Antoine",
		"rights": "This work is shared with the public using the Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0) license.",
		"spread": "",
		"src_url": "http://code.google.com/p/epub-samples/downloads/list",
		"title": "Le Vrai Régime anti-cancer",
		"updated_at": "2012-06-15T00:11:57.065Z"
	}
]